name: Compile LaTeX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up LaTeX
      run: sudo apt-get install -y texlive-full

    - name: Compile LaTeX File
      run: |
        pdflatex thesis.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: compiled-thesis
        path: thesis.pdf
